import jsPDF from 'jspdf';
import autoTable from 'jspdf-autotable';
import { StudentResult } from '@/types/result';

export const generatePDFReport = (student: StudentResult) => {
    const doc = new jsPDF();

    // -- Header --
    // University Name
    doc.setFontSize(18);
    doc.setFont('helvetica', 'bold');
    doc.text("UNIVERSITY OF AGRICULTURE, FAISALABAD", 105, 15, { align: "center" });

    // Subtitle
    doc.setFontSize(14);
    doc.setFont('helvetica', 'normal');
    doc.text("Detailed Marks Certificate / Result Card", 105, 23, { align: "center" });

    // Divider
    doc.setLineWidth(0.5);
    doc.line(14, 28, 196, 28);

    // -- Student Info (Left) --
    doc.setFontSize(10);
    doc.setFont('helvetica', 'bold');

    let yPos = 38;
    const leftColX = 14;
    const rightColX = 120;

    doc.text(`Name:`, leftColX, yPos);
    doc.setFont('helvetica', 'normal');
    doc.text(student.name, leftColX + 25, yPos);

    doc.setFont('helvetica', 'bold');
    doc.text(`Registration:`, rightColX, yPos);
    doc.setFont('helvetica', 'normal');
    doc.text(student.registrationNo.toUpperCase(), rightColX + 25, yPos);

    doc.setFont('helvetica', 'normal');
    doc.text(student.registrationNo.toUpperCase(), rightColX + 25, yPos);

    // Removed Degree field as requested

    // -- Summary Stats (Box) --
    yPos += 10;

    doc.setFillColor(245, 245, 245);
    doc.roundedRect(14, yPos, 182, 18, 2, 2, 'F');

    doc.setFontSize(11);
    doc.setTextColor(0, 0, 0);

    doc.setFont('helvetica', 'bold');
    doc.text(`CGPA: ${student.cgpa.toFixed(2)}`, 30, yPos + 11);
    doc.text(`Credit Hours: ${student.totalCreditHours}`, 150, yPos + 11);

    yPos += 25;

    // -- Semester Tables --

    // reverse() usually sorts latest first in UI, but for transcript we often want specific order.
    // We'll trust the current order in the object matches user preference or reverse if needed.
    // Usually transcripts are Semester 1 -> N. The object might be N -> 1.
    // Let's create a copy and sort by semester number for the report.
    const semestersForReport = [...student.semesters].sort((a, b) => a.semesterNumber - b.semesterNumber);

    semestersForReport.forEach((sem) => {
        // Check for page break
        if (yPos > 250) {
            doc.addPage();
            yPos = 20;
        }

        // Semester Header
        doc.setFontSize(12);
        doc.setFont('helvetica', 'bold');
        doc.setFillColor(230, 230, 230);
        // Draw a small bar
        doc.rect(14, yPos - 5, 182, 7, 'F');
        doc.text(`${sem.semester} (GPA: ${sem.gpa.toFixed(2)})`, 16, yPos);

        // Table Body
        const tableBody = sem.subjects.map(sub => [
            sub.code || "-",
            sub.name,
            sub.creditHours,
            sub.marks || "-",
            sub.grade,
            sub.gradePoints.toFixed(2)
        ]);

        autoTable(doc, {
            startY: yPos + 4,
            head: [['Code', 'Course Title', 'Cr. Hrs', 'Marks', 'Grade', 'G.P']],
            body: tableBody,
            theme: 'grid',
            headStyles: {
                fillColor: [40, 40, 40],
                fontSize: 9,
                halign: 'center'
            },
            bodyStyles: {
                fontSize: 9
            },
            columnStyles: {
                0: { cellWidth: 25 },
                1: { cellWidth: 'auto' }, // Title gets remaining
                2: { cellWidth: 15, halign: 'center' },
                3: { cellWidth: 15, halign: 'center' },
                4: { cellWidth: 15, halign: 'center' },
                5: { cellWidth: 15, halign: 'center' }
            },
            styles: {
                cellPadding: 3
            },
            margin: { left: 14, right: 14 }
        });

        // Update yPos for next loop
        yPos = (doc as any).lastAutoTable.finalY + 15;
    });

    // Footer Disclaimer
    const pageCount = (doc as any).internal.getNumberOfPages();
    for (let i = 1; i <= pageCount; i++) {
        doc.setPage(i);
        doc.setFontSize(8);
        doc.setTextColor(100);
        doc.text(`Generated by UAF Calc (Unofficial) - ${new Date().toLocaleDateString()}`, 14, 285);
        doc.text(`Page ${i} of ${pageCount}`, 196, 285, { align: 'right' });
    }

    doc.save(`${student.registrationNo}_Transcript.pdf`);
};
